.PHONY:
.NOTPARALLEL:

install:
	@echo "Installing Hue Automation Scripts"

start:
	@echo "Starting Hue Automation"

logs:
	@echo "Getting Logs"

stop:
	@echo "Stopping Hue Automation"

uninstall:
	@echo "Uninstalling Hue Automation Scripts"
